# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeodataAPICollection
                                 A QGIS plugin
 This plugin allow you to access a series of geodata published via APIs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-10
        copyright            : (C) 2019 by Diego F Malacarne
        email                : diego.malacarne@yahoo.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeodataAPICollection class from file GeodataAPICollection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FHR_data import GeodataAPICollection
    return GeodataAPICollection(iface)
